name = "password-manager"
compatibility_date = "2026-03-09"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "password_manager"
database_id = "5de0be9e-11dc-4705-8577-a6a431b8e24b"
